# Generated by Django 2.2.7 on 2019-11-05 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceBroadcastApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 0, 50, 30, 154528)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 0, 50, 30, 153529)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 0, 50, 30, 152539)),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 0, 50, 30, 152539)),
        ),
    ]
