# Generated by Django 2.2.7 on 2019-11-06 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceBroadcastApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 14, 47, 53, 8730)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 14, 47, 53, 7732)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 14, 47, 53, 6735)),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 14, 47, 53, 6735)),
        ),
    ]
