# Generated by Django 2.2.7 on 2019-11-06 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceBroadcastApp', '0002_auto_20191106_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 15, 11, 14, 124233)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 15, 11, 14, 123236)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 15, 11, 14, 122239)),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 15, 11, 14, 122239)),
        ),
    ]
