# Generated by Django 2.2.7 on 2019-11-05 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceBroadcastApp', '0003_auto_20191105_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 22, 35, 45, 626393)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 22, 35, 45, 625395)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 22, 35, 45, 624398)),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_book',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_book',
            field=models.ManyToManyField(to='voiceBroadcastApp.PhoneBook'),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 22, 35, 45, 623401)),
        ),
    ]
