# Generated by Django 2.2.7 on 2019-11-06 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voiceBroadcastApp', '0005_auto_20191106_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voiceBroadcastApp.Campaign'),
        ),
        migrations.AddField(
            model_name='call',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='call',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 20, 58, 47, 283579)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 20, 58, 47, 282582)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 20, 58, 47, 281586)),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 20, 58, 47, 281586)),
        ),
    ]
